Issue #198 Fix bug introduced in previous commit: tests/rest/auth/test_config.py:163: AttributeError AttributeError: 'function' object has no attribute 'st_mode'